# Generated by Django 5.1.3 on 2025-01-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='user',
        ),
        migrations.AddField(
            model_name='otp',
            name='phone',
            field=models.CharField(default=1, max_length=12, verbose_name='تلفن کاربر'),
            preserve_default=False,
        ),
    ]
