# Generated by Django 5.1.3 on 2024-11-12 13:32

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_remove_comment_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Created',
        ),
        migrations.AddField(
            model_name='comment',
            name='Approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='Created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
