# Generated by Django 5.1.3 on 2024-11-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_remove_comment_created_comment_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Phone',
            field=models.TextField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Created_at',
            field=models.DateField(),
        ),
    ]
