# Generated by Django 5.1.3 on 2024-12-04 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_image',
            old_name='img',
            new_name='imgs',
        ),
    ]
