# Generated by Django 5.1.3 on 2025-01-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0009_rename_img_profile_image_imgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='Birthday',
            field=models.DateField(verbose_name='تاریخ تولد'),
        ),
    ]
