# Generated by Django 5.1.3 on 2025-01-18 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0010_alter_information_birthday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile_image',
        ),
    ]
