# Generated by Django 5.1.3 on 2025-01-19 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0011_delete_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adress',
            options={'verbose_name': 'آدرس', 'verbose_name_plural': 'آدرس ها'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterModelOptions(
            name='information',
            options={'verbose_name': 'اطلاعات', 'verbose_name_plural': 'اطلاعات ها'},
        ),
        migrations.AlterField(
            model_name='adress',
            name='adress',
            field=models.TextField(max_length=3000, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Approved',
            field=models.BooleanField(default=False, verbose_name='حالت نمایش'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Comment_message',
            field=models.TextField(max_length=2000, verbose_name='متن نظر'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Created_at',
            field=models.DateField(verbose_name='نوشته شده در'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Full_name',
            field=models.CharField(max_length=300, verbose_name='نام کامل'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Phone',
            field=models.TextField(max_length=15, null=True, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='information',
            name='Email',
            field=models.EmailField(max_length=200, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='information',
            name='Phone',
            field=models.CharField(max_length=15, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='information',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
