# Generated by Django 5.1.3 on 2024-12-08 16:49

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Remind_member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Full_name', models.CharField(max_length=100)),
                ('Date_remind', django_jalali.db.models.jDateField()),
                ('Befor_day_remind', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
