# Generated by Django 5.1.3 on 2024-12-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remind_member',
            name='Date_remind',
            field=models.DateField(),
        ),
    ]
