# Generated by Django 5.1.3 on 2025-01-19 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_alter_remind_member_date_remind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remind_member',
            options={'verbose_name': 'یادآور', 'verbose_name_plural': 'یادآوری ها'},
        ),
        migrations.AlterField(
            model_name='remind_member',
            name='Befor_day_remind',
            field=models.IntegerField(verbose_name='یادآوری در این تعداد روز قبل'),
        ),
        migrations.AlterField(
            model_name='remind_member',
            name='Date_remind',
            field=models.DateField(verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='remind_member',
            name='Full_name',
            field=models.CharField(max_length=100, verbose_name='نام یادآور'),
        ),
        migrations.AlterField(
            model_name='remind_member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
