# Generated by Django 5.1.3 on 2024-12-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Img', models.ImageField(upload_to='')),
                ('Name_Product', models.CharField(max_length=100)),
                ('Caption', models.CharField(max_length=1000)),
                ('Price', models.CharField(max_length=15)),
                ('Discount', models.CharField(max_length=3)),
            ],
        ),
    ]
