# Generated by Django 5.1.3 on 2024-12-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='selected_options',
            field=models.TextField(blank=True, null=True),
        ),
    ]
