# Generated by Django 5.1.3 on 2024-12-26 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_products_description_alter_products_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('User_name', models.CharField(max_length=100)),
                ('Question', models.TextField(max_length=250)),
                ('Answer', models.TextField(max_length=250, null=True)),
                ('Approved', models.BooleanField(default=False)),
                ('Created_at', models.DateField()),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.products')),
            ],
        ),
    ]
