# Generated by Django 5.1.3 on 2024-12-30 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_alter_comment_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='User_name',
            new_name='User_id',
        ),
    ]
