# Generated by Django 5.1.3 on 2024-12-30 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_rename_user_name_comment_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='User_id',
            new_name='User',
        ),
    ]
