# Generated by Django 5.1.3 on 2024-12-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_rename_user_id_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Approved',
            field=models.BooleanField(default=False),
        ),
    ]
