# Generated by Django 5.1.3 on 2024-12-31 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_comment_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
