# Generated by Django 5.1.3 on 2025-01-01 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0011_remove_questions_user_name_questions_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlike',
            name='is_like',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Product_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Shop.products'),
            preserve_default=False,
        ),
    ]
