# Generated by Django 5.1.3 on 2025-01-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0015_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='FinalPrice',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='NumberProduct',
            field=models.IntegerField(default=1),
        ),
    ]
