# Generated by Django 5.1.3 on 2025-01-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0016_cart_finalprice_cart_numberproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Message',
            field=models.TextField(null=True),
        ),
    ]
