# Generated by Django 5.1.3 on 2025-01-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0020_orders_user_alter_orders_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='user',
        ),
        migrations.AddField(
            model_name='orders',
            name='user_adress',
            field=models.TextField(null=True, verbose_name='آدرس مشتری'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user_name',
            field=models.CharField(max_length=200, null=True, verbose_name='مشتری'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user_phone',
            field=models.TextField(null=True, verbose_name='تلفن مشتری'),
        ),
    ]
