# Generated by Django 5.1.3 on 2025-01-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0021_remove_orders_user_orders_user_adress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='ref_id',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
