# Generated by Django 5.1.3 on 2025-01-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0024_orders_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='message_order',
            field=models.TextField(null=True, verbose_name='پیام همراه با سفارش'),
        ),
    ]
